apiVersion: batch/v1
kind: Job
metadata:
  name: post-upgrade-database-{{ include "helm-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm-chart.name" . }}
    helm.sh/chart: {{ include "helm-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    spec:
      containers:
      - name: rails-db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c", "sh lib/docker/execute-mounted-command.sh rails db:migrate"]
        env:
        {{- range $k, $v := .Values.env }}
          - name: {{ $k }}
            value: {{ $v }}
        {{- end }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}
      restartPolicy: Never
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
   
  backoffLimit: 4
